# Generated by Django 4.0.3 on 2022-03-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
