# Generated by Django 4.0.3 on 2022-03-20 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_room_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
