# Generated by Django 4.0.3 on 2022-04-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_schedule_time_slot_roompresent_roomaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='authorized_present',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='room',
            name='max_occupancy',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='room',
            name='room_alert_email',
            field=models.EmailField(default='trackerelearning@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='roompresent',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.room'),
        ),
    ]
