# Generated by Django 3.2.4 on 2022-04-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_schedule_time_slot_roompresent_roomaccesslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='remote_management_permission',
        ),
        migrations.AddField(
            model_name='room',
            name='room_alert_email',
            field=models.EmailField(default='trackerelearning@gmail.com', max_length=254),
        ),
    ]
