# Generated by Django 4.0.3 on 2022-04-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220419_2250'),
        ('home', '0009_remove_profile_remote_management_permission_and_more'),
    ]

    operations = [
    ]
